# See https://github.com/foundry-rs/foundry/tree/master/foundry for more information

[profile.default]
src = "src"

test = "test"
# remappings = ["openzeppelin-contracts=lib/openzeppelin-contracts"]
# You can define additional settings per profile

[profile.release]
# release profile settings

[profile.ci]
# continuous integration settings
