# .github/workflows/ci.yml
name: CI

# Déclencheurs : on push et pull_request sur la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Installer Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Mettre en cache le cache Foundry
        uses: actions/cache@v3
        with:
          path: ~/.foundry
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Installer les dépendances
        run: $HOME/.foundry/bin/forge install --no-progress

      - name: Vérifier le format du code
        run: $HOME/.foundry/bin/forge fmt --check

      - name: Compiler avec rapports de taille
        run: $HOME/.foundry/bin/forge build --sizes

      - name: Exécuter les tests
        run: $HOME/.foundry/bin/forge test -vvv
