 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
           submodules: recursive

       - name: Install Foundry
         run: |
           curl -L https://foundry.paradigm.xyz | bash
-          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
+          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

       - name: Cache Foundry cache
         uses: actions/cache@v3
         with:
           path: ~/.foundry
           key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}
           restore-keys: |
             ${{ runner.os }}-foundry-

       - name: Install dependencies
-        run: forge install --no-progress
+        run: $HOME/.foundry/bin/forge install --no-progress

       - name: Check code formatting
-        run: forge fmt --check
+        run: $HOME/.foundry/bin/forge fmt --check

       - name: Build with size metrics
-        run: forge build --sizes
+        run: $HOME/.foundry/bin/forge build --sizes

       - name: Run tests
-        run: forge test -vvv
+        run: $HOME/.foundry/bin/forge test -vvv
