name: Update Gas Price

on:
  schedule:
    - cron: '*/5 * * * *'  # Toutes les 5 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run updatePrice script
        env:
          DEPLOYER_KEY: ${{ secrets.DEPLOYER_KEY }}
          ARB_SEPOLIA_RPC: ${{ secrets.ARB_SEPOLIA_RPC }}
          CHAINLINK_FEED_SEPOLIA: ${{ secrets.CHAINLINK_FEED_SEPOLIA }}
        run: node scripts/updatePrice.js
